version: '3.8'

services:
  backend-jenkins:
    build: ./backend
    container_name: backend_jenkins
    ports:
      - "8889:8888"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend-jenkins:
    build: ./frontend
    container_name: frontend_jenkins
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-jenkins
